"""init

Revision ID: dead48d60a26
Revises: 
Create Date: 2026-03-31 11:03:25.779730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dead48d60a26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('re_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('re_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('re_cost', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('re_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('re_group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('re_id', name=op.f('reports_pkey'))
    )
    op.create_table('orders',
    sa.Column('ord_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ord_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ord_re', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ord_re'], ['reports.re_id'], name=op.f('orders_ord_re_fkey')),
    sa.PrimaryKeyConstraint('ord_id', name=op.f('orders_pkey'))
    )
    op.drop_table('hotels')
    # ### end Alembic commands ###
